
// Resource.h - generated by hand by Warren Moore :)

#ifndef LESSON38_RESOURCE_H
#define LESSON38_RESOURCE_H

#define IDB_BUTTERFLY1                  115
#define IDB_BUTTERFLY2                  116
#define IDB_BUTTERFLY3                  117

#endif
