SUBDIRS= \
	lesson01 \
	lesson02 \
	lesson03 \
	lesson04 \
	lesson05 \
	lesson06 \
	lesson07 \
	lesson08 \
	lesson09 \
	lesson10 \
	lesson11 \
	lesson12 \
	lesson13 \
	lesson16 \
	lesson17 \
	lesson18 \
	lesson19 \
	lesson20 \
	lesson21 \
	lesson25 \
	lesson28 \
	lesson29 \
	lesson30 \
	lesson31 \
	lesson33 \
	lesson34 \
	lesson36 \
	lesson37 \
	lesson48

all:
	for d in $(SUBDIRS); do $(MAKE) -C $$d ; done

clean:
	for d in $(SUBDIRS); do $(MAKE) -C $$d clean; done
